### PR TITLE
fix(combo): replace p tag with span and remove default height

### LINKED ISSUE #2174: Combo is not showing items visually correct
## Description  
Combo items are not displayed visually correct.

 * ignite-ui version: 
 * browser: 

## Steps to reproduce  

1. Go to this [JsFiddle](http://jsfiddle.net/gh/get/jquery/1.9.1/igniteuisamples/jsfiddle-samples/tree/master/EN/HtmlSamples/combo/templates/)
2. Open the Combo and observe

## Result  
image

## Expected result  
image

### PR DESCRIPTION
**Pull request by Volen99**
Closes #2174, #2198

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR contains breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: tests/unit/combo/rendering/rendering-test.js [hunk 1]
```diff
@@ -478,7 +478,7 @@ QUnit.test('[ID7] igCombo scrolling tests', function (assert) {
 	assert.equal(combo.listScrollTop(), 200, "When value is undefined, then scroll top is returned.");
 	assert.equal($dropDownCont.prop('scrollTop'), 200, "Drop down container should be equal to set top scroll.");
 
-	scrollHeight = $dropDownCont.prop('scrollHeight') - $dropDownCont.innerHeight();
+	scrollHeight = Math.round( $dropDownCont.prop('scrollHeight') - $dropDownCont.innerHeight() + 0.188);
```
Comment (hanastasov) [inline tests/unit/combo/rendering/rendering-test.js:481]: Can't we avoid adding 0.188? Isnt this the aim of rounding - to avoid digits after the . ?

Comment (Volen99) [reply tests/unit/combo/rendering/rendering-test.js:481]: Oh, of course we can. I forgot to remove it. Will remove it now :|

File: tests/unit/combo/rendering/rendering-test.js [hunk 2]
```diff
@@ -478,7 +478,7 @@ QUnit.test('[ID7] igCombo scrolling tests', function (assert) {
 	assert.equal(combo.listScrollTop(), 200, "When value is undefined, then scroll top is returned.");
 	assert.equal($dropDownCont.prop('scrollTop'), 200, "Drop down container should be equal to set top scroll.");
 
-	scrollHeight = $dropDownCont.prop('scrollHeight') - $dropDownCont.innerHeight();
+	scrollHeight = Math.round( $dropDownCont.prop('scrollHeight') - $dropDownCont.innerHeight());
```
Comment (hanastasov) [inline tests/unit/combo/rendering/rendering-test.js:481]:
```suggestion
	scrollHeight = Math.round($dropDownCont.prop('scrollHeight') - $dropDownCont.innerHeight());
```

**Review by hanastasov — CHANGES_REQUESTED** [review]
