### PR TITLE
Runtime locale changes - initial implementation

### LINKED ISSUE #1049: Editors render redundant attributes (title vs. aria-label) on buttons
### Description  
The Editor controls render redundant attributes on the drop down buttons, spin buttons, and clear buttons. Both `title` and `aria-label` are rendered for the elements with `role=button`.

### Steps to reproduce  

1. Check either of these methods:
```
_renderDropDownButton
_renderSpinButtons
_renderClearButton
```

### Result  
The result is that under some screen readers all attributes will be read to the user, resulting in text of the sort:
"Button, Spin Up, Spin Up Button"

### Expected result  
Redundant attributes should be avoided in order to improve the accessibility of the control. The control is accessible now, but it may be a little _overly accessible_ at times.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by kdinev**
Closes #1049

### CODE REVIEW

File: build/packages/combined-files.js [hunk 1]
```diff
@@ -113,6 +113,7 @@ module.exports = {
                     "./dist/js/modules/infragistics.util.jquerydeferred.js",
                     "./dist/js/modules/infragistics.datasource.js",
                     "./dist/js/modules/infragistics.templating.js",
+					"./dist/js/modules/infragistics.ui.widget.js",
```
Comment (ChronosSF) [inline build/packages/combined-files.js]: Looks like a small indentation issue.

File: src/js/infragistics.loader.js [hunk 2]
```diff
@@ -874,12 +882,13 @@ $.ig.dependencies = [
 	{
 		widget: "igCombo",
 		dependency: [
-			{ name: "igUtil" },
+			{ name: "igWidget" },
+			{ name: "igWidget" },
```
Comment (ChronosSF) [inline src/js/infragistics.loader.js]: The line is duplicated.

File: src/js/modules/infragistics.ui.combo.js [hunk 3]
```diff
@@ -32,6 +32,7 @@
 			"jquery-ui",
 			"./infragistics.util",
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.combo.js]: If widget depends on util do we need to specify the combo depends on both util and widget?

File: src/js/modules/infragistics.ui.combo.js [hunk 4]
```diff
@@ -1620,6 +1621,9 @@
             };
 
             this._analyzeOptions();
+
+			// Options related to localization
+			this._changeLocale();
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.combo.js]: Looks like a small indentation issue. Could be because the other lines use spaces.

File: src/js/modules/infragistics.ui.widget.js [hunk 5]
```diff
@@ -0,0 +1,119 @@
+/*!@license
+ * Infragistics.Web.ClientUI Toolbar <build_number>
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.widget.js]: Maybe a copy-pasted string "Toolbar"?

File: src/js/modules/infragistics.ui.widget.js [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+                });
+
+                // Get
+                var regional = $(".selector").igWidget("option", "regional");
+
+                // Set
+                $(".selector").igWidget("option", "regional", "ja");
+            ```
+            */
+            regional: "en-US"
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.widget.js]: Looks to be using spaces - the review page has indentation issues.

File: src/js/modules/infragistics.ui.editors.js [hunk 7]
```diff
@@ -5176,14 +5173,14 @@
...
-						$.ig.util.stringFormat($.ig.Editor.locale.maxValExceedSetErrMsg,
+						$.ig.util.stringFormat(this._getLocaleValue("maxValExceedSetErrMsg"),
 							this.options.maxValue));
 				} else if (!isNaN(this.options.minValue) && newValue < this.options.minValue) {
 					newValue = this.options.minValue;
 
 					// Raise Warning level 2
 					this._sendNotification("warning",
-						$.ig.util.stringFormat($.ig.Editor.locale.minValExceedSetErrMsg,
+						$.ig.util.stringFormat(this._getLocaleValue("maxValExceedSetErrMsg"),
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.editors.js]: Please, check if you didn't change minValExceedSetErrMsg with maxValExceedSetErrMsg

File: src/js/modules/infragistics.ui.editors.js [hunk 8]
```diff
@@ -5758,7 +5755,7 @@
 
 							// Raise Warning level 2
 							this._sendNotification("warning",
-								$.ig.util.stringFormat($.ig.Editor.locale.minValExceedSetErrMsg,
+								$.ig.util.stringFormat(this._getLocaleValue("maxValExceedSetErrMsg"),
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.editors.js]: Please, check if you didn't change minValExceedSetErrMsg with maxValExceedSetErrMsg

File: src/js/modules/infragistics.ui.editors.js [hunk 9]
```diff
@@ -6071,15 +6068,15 @@
...
+						$.ig.util.stringFormat(this._getLocaleValue("maxValExceedSetErrMsg"),
 							this.options.maxValue));
 				} else if (!isNaN(this.options.minValue) &&
 					newValue / this.options.displayFactor < this.options.minValue) {
 					newValue = this.options.minValue * this.options.displayFactor;
 
 					//Notify
 					this._sendNotification("warning",
-						$.ig.util.stringFormat($.ig.Editor.locale.minValExceedSetErrMsg,
+						$.ig.util.stringFormat(this._getLocaleValue("maxValExceedSetErrMsg"),
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.editors.js]: Please, check if you didn't change minValExceedSetErrMsg with maxValExceedSetErrMsg

File: src/js/modules/infragistics.ui.combo.js (hunk 3 above)
Comment (kdinev) [inline src/js/modules/infragistics.ui.combo.js]: Nope we don't. I'll fix this.

Comment (kdinev) [inline src/js/modules/infragistics.ui.combo.js]: I'll also remove jquery and jquery-ui, since they are dependencies for widget as well.

File: src/js/modules/infragistics.ui.widget.js (hunk 5 above)
Comment (kdinev) [inline src/js/modules/infragistics.ui.widget.js]: Not maybe. Certainly.

File: src/js/modules/infragistics.ui.widget.js [hunk 10]
```diff
@@ -0,0 +1,137 @@
...
+
+                // Set
+                $(".selector").igWidget("option", "regional", "ja");
+            ```
+            */
+			regional: "en-US"
+		},
+		_setOption: function (option, value) {
+			var prevValue = this.options[ option ];
+			if (prevValue === value) {
```
Comment (ChronosSF) [inline src/js/modules/infragistics.ui.widget.js]: As discussed, if locale and regional can be an object, getting the option value, changing some props and setting it back will not result in a change because of this line.

**Comment by kdinev** [comment]
@ChronosSF Addressed.

**Comment by kdinev** [comment]
@m-hristov I checked the tile manager code and the reference to the splitter locale is not a correct implementation and should be changed. The error really belongs to the tile manager context, because the option is not settable in the tile manager context. This will be changes to reference an error message from the tile manager locale.

I don't think that implementation which includes passing a widget name as a parameter in each function, and then calling getWidgetName again in each function is good.

File: src/js/modules/infragistics.ui.widget.js [hunk 11]
```diff
@@ -0,0 +1,133 @@
...
+    /*
+		Base igWidget for all Ignite UI widgets.
+	*/
+    $.widget("ui.igWidget", {
+		localeWidgetName: null,
+        options: {
+            /* type="string|object" Set/Get the locale setting for the widget.
+            ```
+                 //Initialize
+                $(".selector").igWidget({
```
Comment (bazal4o) [inline src/js/modules/infragistics.ui.widget.js]: If we want the same code snippet to appear in all the inherited widget we should use %%WidgetName%% placeholder instead of igWidget

**Comment by kdinev** [comment]
@m-hristov The structure of the null texts should follow the locale format.
